# Generated by Django 2.1.3 on 2018-11-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead_mgt.Lead'),
            preserve_default=False,
        ),
    ]
