# Generated by Django 2.1.3 on 2018-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0002_interaction_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
