# Generated by Django 2.1.3 on 2018-11-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0004_lead_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('unreachable', 'unreachable'), ('wrong_number', 'wrong number'), ('converted', 'converted'), ('not_interested', 'not interested'), ('not_expired', 'not expired'), ('call_later', 'call later'), ('quoted', 'quoted'), ('bad_line', 'bad line')], default='submitted', max_length=30),
        ),
    ]
