# Generated by Django 2.1.3 on 2018-12-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0008_auto_20181202_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='close_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='call',
            name='open_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
