# Generated by Django 2.1.3 on 2018-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0009_auto_20181202_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('unreachable', 'unreachable'), ('unreachable_follow_up', 'unreachable follow up'), ('wrong_number', 'wrong number'), ('converted', 'converted'), ('not_interested', 'not interested'), ('not_expired', 'not expired'), ('call_later', 'call later'), ('quoted', 'quoted'), ('bad_line', 'bad line')], default='submitted', max_length=30),
        ),
    ]
