# Generated by Django 2.1.3 on 2018-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0010_auto_20181204_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='lead',
            field=models.IntegerField(),
        ),
    ]
