# Generated by Django 2.1.3 on 2018-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0012_auto_20181205_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_date',
            field=models.DateField(),
        ),
    ]
