# Generated by Django 2.1.3 on 2018-12-05 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0013_auto_20181205_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='database_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
