# Generated by Django 2.1.3 on 2018-12-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0014_interaction_database_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='batch_numder',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
