# Generated by Django 2.1.3 on 2018-12-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0015_interaction_batch_numder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='batch_numder',
            new_name='batch_number',
        ),
    ]
