# Generated by Django 2.1.3 on 2018-12-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0016_auto_20181205_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawCallData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField()),
                ('database_date', models.DateTimeField(auto_now_add=True)),
                ('lead_id', models.CharField(max_length=20)),
                ('lead_date', models.CharField(max_length=20)),
                ('lead_name', models.CharField(max_length=160)),
                ('lead_phone', models.CharField(max_length=50)),
                ('current_status', models.CharField(max_length=50)),
                ('current_next_call', models.CharField(blank=True, max_length=50)),
                ('agent_id', models.CharField(blank=True, max_length=50)),
                ('call_date', models.CharField(blank=True, max_length=20)),
                ('disposition', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('new_next_call', models.CharField(blank=True, max_length=20)),
                ('policy_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
