# Generated by Django 2.1.3 on 2018-12-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0017_rawcalldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcalldata',
            name='new_next_call',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
