# Generated by Django 2.1.3 on 2018-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0018_auto_20181208_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcalldata',
            name='notes',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='rawcalldata',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
