# Generated by Django 2.1.3 on 2019-01-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_mgt', '0024_profile_ecocash_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsEarned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_date', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('affiliate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead_mgt.Lead')),
            ],
        ),
        migrations.RenameModel(
            old_name='Points',
            new_name='PointSchedule',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='policy_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(null=True),
        ),
    ]
