# Generated by Django 2.1.3 on 2019-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0025_auto_20190104_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('ftp', 'third party'), ('comp', 'comprehensive')], max_length=20),
        ),
    ]
