# Generated by Django 2.1.3 on 2019-01-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0026_vehicle_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20),
        ),
    ]
