# Generated by Django 2.1.3 on 2019-01-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0027_auto_20190106_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
    ]
