# Generated by Django 2.1.3 on 2019-01-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_mgt', '0028_redemptionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionschedule',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
